### ISSUE TITLE
YTKNetwork 2.0.x ToDo List

### ISSUE THREAD

**Issue by lancy** [yuantiku/YTKNetwork#224]
目前发现的 2.0 版本的问题：

- [x] 2. 新增的`responseSerializerType`默认为 `.JSON`，会导致 response 不是 JSON 的请求失败，需要在迁移指南里说明

- [x] 3.`baseUrl`和`requestUrl`的拼接规则有修改，需要在文档中说明（添加 `buildRequestUrl` 测试用例）

- [X] 6. 在请求初始化以及响应处理的时候，将可能发生的错误通过 `request.error` 暴露出来（而不只是打出 log）。

- [ ] 7. <del>对于部分需要调用 super 的重载方法，使用 `NS_REQUIRES_SUPER` 标注，防止使用错误。</del>(Later)

- [X] 8. <del>使用 `NSParameterAssert` 对一些 API 的输入进行限制，减少函数内部逻辑层级。</del>(Later)

- [X] 10. `YTKChainRequest`和`YTKBatchRequest`不在允许设置单个`request`的`completionBlock`。

- [X] 11. README.md 中英文分开，里面加上 MigrationGuide.md 链接。 

- [X]  12. 增加 Changelog

2.0.1 fixed:
- [x] 1. `YTKBaseRequest`中`@property (nonatomic, readonly, getter=isExecuting) BOOL isExecuting`需要修改为`@property (nonatomic, readonly, getter=isExecuting) BOOL executing`

- [x] 4. `maxConcurrentCount`不再能够限制并发请求，将相关代码删除，保持和 AFNetworking 一致

- [x] 5. `CFNetwork`需要显示加为依赖来避免 iOS 8.1 上的 Crash

- [x] 9. `startWithoutCache` 和 `ignoreCache` 在 2.x 版本会清理掉缓存，而 1.x 版本则仅仅是忽略缓存，需要改回 1.x 版本的行为，以符合 without 和 ignore 的语义

**Comment by Huang-Libo** [comment]
时刻关注着

**Comment by maojj** [comment]
2.0.1 fixed：1，4，5，9

**Comment by LeeJeanYi** [comment]
请问下,现在的缓存比如设置1个小时,在这时间内,我要如何更新接口的缓存数据?教程里的方法,用起来是没用的,请求回调的数据是空的,只有缓存数据.

**Comment by skyline75489** [comment]
调用 `startWithoutCache` 方法，可以更新缓存数据。

**Comment by LeeJeanYi** [comment]
再麻烦一下,startWithoutCache 有回调吗? 是请求前还是请求后调用呢?

**Comment by skyline75489** [comment]
同样的 request 实例还是会使用旧的 request 回调

**Comment by skyline75489** [comment]
@jzy673378715  YTKRequest 暴露出了 currentRequest 和 originalRequest 两个属性用于区分重定向。请问你说的处理具体指的是什么？

**Comment by LeeJeanYi** [comment]
可以更新下demo里的缓存更新这个吗?我还是没研究出来怎么来刷新缓存数据,或者给一段代码

**Comment by skyline75489** [comment]
@LeeJeanYi  你现在用的代码是什么样子的？

**Comment by LeeJeanYi** [comment]
` discoveryBannerAPI * banner_api=[[discoveryBannerAPI alloc] initWithBannerType:@"7"];
   

    discoveryTopicAPI * topic_api=[[discoveryTopicAPI alloc] initWithTopicId:@""];


    discoveryCircleHotAPI * circleHot_api=[[discoveryCircleHotAPI alloc]initWithCircleHotAPI];


    discoveryHotPostAPI * infoHot_api=[[discoveryHotPostAPI alloc]initWithHotPostAPI];
    
    YTKBatchRequest * batchRequest=[[YTKBatchRequest alloc]initWithRequestArray:@[banner_api,topic_api,circleHot_api,infoHot_api]];
`

`[batchRequest startWithCompletionBlockWithSuccess:^(YTKBatchRequest *batchRequest) {

      //获取数据了

    }    
`
现在不晓得要在哪里去调用startwithoutcache..

**Comment by lancy** [comment]
设置`ignoreCache`为`YES`，再调用`start`的效果，是和`startWithoutCache`一致的；
`batchRequest`和`chainRequest`只能调用`start`，所以想要强制更新需要把`request`加入`batchRequest`之前，设置上`ignoreCache`

**Comment by lancy** [comment]
btw，请不要在这个 issue 里面问问题了..请开一个新 issue，稍后我会把这个 issue 下的无关评论删除
